package app.view;

import app.model.KhuyenMai;
import app.model.Voucher;
import app.service.KhuyenMaiService;
import app.service.VoucherService;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KhuyenMaiMainPanel extends javax.swing.JPanel {

    private VoucherService ss = new VoucherService();
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<Voucher> listKM = new ArrayList<>();
    private int index = -1;

    public KhuyenMaiMainPanel() {
        initComponents();
        cboLoaiGiamInsert.removeAllItems();
        cboLoaiGiamInsert.addItem("Dành Cho Khách Hàng");
        cboLoaiGiamInsert.addItem("Dành Cho Tất Cả");
        cboLoaigiamTimKiem.removeAllItems();
        cboLoaigiamTimKiem.addItem("Tất cả");
        cboLoaigiamTimKiem.addItem("Dành Cho Khách Hàng");
        cboLoaigiamTimKiem.addItem("Dành Cho Tất Cả");

        this.fillTable(ss.getAll());
    }

    void fillTable(List<Voucher> m) {
        dtm = (DefaultTableModel) tblQLPGG.getModel();
        dtm.setRowCount(0);
        for (Voucher x : m) {
            dtm.addRow(x.toDataRow());
        }
    }

    void showData(int index) {
        txtMa.setText(tblQLPGG.getValueAt(index, 1).toString());
        txtTen.setText(tblQLPGG.getValueAt(index, 2).toString());
        txtGtriAD.setText(tblQLPGG.getValueAt(index, 4).toString());
        try {
            Date date1 = new SimpleDateFormat("yyyy-MM-dd")
                    .parse(tblQLPGG.getValueAt(index, 5).toString());
            dataTuNgay.setDate(date1);
            Date date2 = new SimpleDateFormat("yyyy-MM-dd")
                    .parse(tblQLPGG.getValueAt(index, 6).toString());
            dataDenNgay.setDate(date2);
        } catch (Exception e) {
            e.printStackTrace();
        }

        cboLoaiGiamInsert.setSelectedItem(tblQLPGG.getValueAt(index, 3).toString());

    }

    Voucher readForm() {
        String ma, ten, loai;
        ma = txtMa.getText().trim();
        if (ma == null || ma.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mã không được để trống");
            return null;
        }
        ten = txtTen.getText().trim();
        if (ten == null || ten.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống");
            return null;
        }
        int gtri = Integer.parseInt(txtGtriAD.getText().trim());
        if (gtri > 99) {
            JOptionPane.showMessageDialog(this,
                    "Gía trị giảm giá không thể vượt quá 99%");
            return null;
        }
        loai = cboLoaiGiamInsert.getSelectedItem().toString();
        Date start_Date = dataTuNgay.getDate();
        if (start_Date == null) {
            JOptionPane.showMessageDialog(this,
                    "Ngày bắt đầu không được bỏ trống!");
            return null;
        }
        Date end_Date = dataDenNgay.getDate();
        if (end_Date == null) {
            JOptionPane.showMessageDialog(this,
                    "Ngày kết thúc không được bỏ trống!");
            return null;
        }
        if (end_Date.getTime() < start_Date.getTime()) {
            JOptionPane.showMessageDialog(this,
                    "Ngày kết thúc phải sau ngày bắt đầu!");
            return null;
        }

        Date currentDate = new Date();
        try {
            if (end_Date.before(currentDate)) {
                JOptionPane.showMessageDialog(this,
                        "Ngày kết thúc không hợp lệ!");
                return null;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return new Voucher(ten, ma, loai, end_Date, end_Date, gtri);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        cboLoaiGiamInsert = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGtriAD = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        dataTuNgay = new com.toedter.calendar.JDateChooser();
        dataDenNgay = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLPGG = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        cboLoaigiamTimKiem = new javax.swing.JComboBox<>();
        dataTuNgayTimKiem = new com.toedter.calendar.JDateChooser();
        datadenNgayTimKiem = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ PHIẾU GIẢM GIÁ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Mã voucher: ");

        jLabel2.setText("Loại giảm giá: ");

        jLabel3.setText("Tên voucher: ");

        cboLoaiGiamInsert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dành Cho Khách Hàng", "Dành Cho Tất Cả" }));
        cboLoaiGiamInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiGiamInsertActionPerformed(evt);
            }
        });

        jLabel5.setText("Giá trị được áp dụng (%) : ");

        jLabel6.setText("Ngày bắt đầu: ");

        jLabel7.setText("Ngày kết thúc: ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        dataTuNgay.setDateFormatString("yyyy-MM-dd");

        dataDenNgay.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnThem)
                        .addGap(92, 92, 92)
                        .addComponent(btnSua))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(txtTen)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(cboLoaiGiamInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtGtriAD, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(dataTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(dataDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(dataTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(dataDenNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLoaiGiamInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtGtriAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu giảm giá", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel8.setText("Tìm kiếm: ");

        jLabel9.setText("Ngày bắt đầu: ");

        tblQLPGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Loại giảm", "Giá trị được áp dụng", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        tblQLPGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLPGGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLPGG);

        jLabel10.setText("Loại giảm: ");

        jLabel11.setText("Ngày kết thúc: ");

        cboLoaigiamTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dành Cho Khách Hàng", "Dành Cho Tất Cả" }));
        cboLoaigiamTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaigiamTimKiemActionPerformed(evt);
            }
        });

        dataTuNgayTimKiem.setDateFormatString("yyyy-MM-dd");

        datadenNgayTimKiem.setDateFormatString("yyyy-MM-dd");

        jButton5.setText("Lọc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataTuNgayTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLoaigiamTimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datadenNgayTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jButton5)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaigiamTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataTuNgayTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addComponent(datadenNgayTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLPGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLPGGMouseClicked
        // TODO add your handling code here:
        int row = tblQLPGG.getSelectedRow();
        showData(row);

    }//GEN-LAST:event_tblQLPGGMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        int check = JOptionPane.showConfirmDialog(this, "Bạn chắn chắn ?");
        if (check != JOptionPane.YES_OPTION) {
            return;
        }

        // Check Ma Khuyến mãi đã tồn tại chưa
        Voucher voucherExits = this.readForm();
        if (voucherExits == null) {
            return;
        }
        Voucher voucher = ss.findKhuyenMaiByMaKhuyenMai(this.readForm().getMa());
        if (voucher != null) {
            JOptionPane.showMessageDialog(this, "Mã voucher đã tồn tại");
            return;
        }

        if (ss.AddKM(this.readForm()) > 0) {
            JOptionPane.showMessageDialog(this, "thêm thành công");
            this.fillTable(ss.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "thêm thất bại ");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không");

        if (check != JOptionPane.YES_OPTION) {
            return;
        }
        index = tblQLPGG.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn sửa");
        } else {
            String ma = tblQLPGG.getValueAt(index, 1).toString();

            Voucher km = readForm();
            if (km == null) {
                return;
            }
            if (ss.updateKM(ma, km) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                this.fillTable(ss.getAll());
            } else {
                JOptionPane.showConfirmDialog(this, "Sửa thất bại");
            }
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void cboLoaigiamTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaigiamTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaigiamTimKiemActionPerformed

    private void cboLoaiGiamInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiGiamInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiGiamInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboLoaiGiamInsert;
    private javax.swing.JComboBox<String> cboLoaigiamTimKiem;
    private com.toedter.calendar.JDateChooser dataDenNgay;
    private com.toedter.calendar.JDateChooser dataTuNgay;
    private com.toedter.calendar.JDateChooser dataTuNgayTimKiem;
    private com.toedter.calendar.JDateChooser datadenNgayTimKiem;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLPGG;
    private javax.swing.JTextField txtGtriAD;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
